//! Key format interop: validates that keys generated by one library are
//! parseable by the other, and that the same private key produces the same
//! public key in both implementations.

use libsignal_core::curve::{PrivateKey as OfficialPrivateKey, PublicKey as OfficialPublicKey};

#[test]
fn dezire_pubkey_roundtrips_through_official() {
    let kp = libsignal_dezire::vxeddsa::gen_keypair();
    assert_eq!(kp.public.len(), 33);
    assert_eq!(kp.public[0], 0x05);

    let official_pub = OfficialPublicKey::deserialize(&kp.public)
        .expect("official must parse dezire 0x05-prefixed key");
    let reserialized = official_pub.serialize();
    assert_eq!(&kp.public[..], &reserialized[..]);
}

#[test]
fn official_pubkey_parseable_by_dezire() {
    // Generate key with dezire, derive official public key, round-trip through dezire
    let kp = libsignal_dezire::vxeddsa::gen_keypair();
    let official = OfficialPrivateKey::deserialize(&kp.secret).expect("deserialize");
    let official_pub = official.public_key().expect("derive pubkey");
    let serialized = official_pub.serialize(); // 33 bytes with 0x05 prefix

    let mut pub_33 = [0u8; 33];
    pub_33.copy_from_slice(&serialized);
    let decoded = libsignal_dezire::utils::decode_public_key(&pub_33);
    assert!(decoded.is_ok(), "dezire must parse 0x05-prefixed key from official lib");
    assert_eq!(&decoded.unwrap()[..], official_pub.public_key_bytes());
}

#[test]
fn same_private_key_same_public_key() {
    for _ in 0..50 {
        let kp = libsignal_dezire::vxeddsa::gen_keypair();
        let dezire_pub_32: &[u8] = &kp.public[1..];

        let official = OfficialPrivateKey::deserialize(&kp.secret).expect("deserialize");
        let official_pub = official.public_key().expect("derive pubkey");

        assert_eq!(
            dezire_pub_32,
            official_pub.public_key_bytes(),
            "public key derivation must match for same private key"
        );
    }
}

#[test]
fn fixed_key_deterministic_derivation() {
    let priv_bytes: [u8; 32] = [
        0xc8, 0x06, 0x43, 0x9d, 0xc9, 0xd2, 0xc4, 0x76, 0xff, 0xed, 0x8f, 0x25, 0x80, 0xc0,
        0x88, 0x8d, 0x58, 0xab, 0x40, 0x6b, 0xf7, 0xae, 0x36, 0x98, 0x87, 0x90, 0x21, 0xb9,
        0x6b, 0xb4, 0xbf, 0x59,
    ];

    let dezire_pub_33 = libsignal_dezire::vxeddsa::gen_pubkey(&priv_bytes);
    let dezire_pub_32 = &dezire_pub_33[1..];

    let official = OfficialPrivateKey::deserialize(&priv_bytes).expect("deserialize");
    let official_pub = official.public_key().expect("derive pubkey");

    assert_eq!(dezire_pub_32, official_pub.public_key_bytes());
}
